language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
    - sudo apt-get update -qq

install:
    - sudo apt-get -y install qt510base qt510charts-no-lgpl
    - source /opt/qt*/bin/qt*-env.sh

script:
  - qmake CONFIG+=release COMPILE_RESOURCES=yes INSTALL_THEME_ICONS=no PREFIX=/usr
  - lrelease Eqonomize.pro
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - mv Eqonomize*.AppImage Eqonomize.AppImage
  - curl -F "file=@./Eqonomize.AppImage" https://file.io
