.TH EQONOMIZE 1 "7 July 2020"
.SH NAME
eqonomize \- A personal accounting software
.SH SYNOPSIS
.B eqonomize
.RI [ options ]
.RI [ url ]
.SH DESCRIPTION
Eqonomize! is a cross-platform personal accounting software, with focus on
efficiency and ease of use for small households. Eqonomize! provides a complete
solution, with bookkeeping by double entry and support for scheduled recurring
transactions, security investments, and budgeting. It gives a clear overview of
past and present transactions, and development of incomes and expenses, with
descriptive tables and charts, as well as an approximation of future account
values.
.SH OPTIONS
.PP
.TP 8
.B \-e, \-\-expenses
Start with expenses list displayed
.PP
.TP 8
.B \-i, \-\-incomes
Start with incomes list displayed
.PP
.TP 8
.B \-\-transfers
Start with transfers list displayed
.PP
.TP 8
.B \-s, \-\-sync
Synchronize file
.PP
There are additional general options (not specific for the application) which
can be listed with
.B \-\-help\-all
.SH "SEE ALSO"
Full documentation at
.I https://eqonomize.github.io/manual/
or in the Help menu
.SH BUGS
Please report any bugs at
.I https://github.com/Eqonimize/eqonomize/issues
.SH AUTHORS
eqonomize was written by Hanna Knutsson <hanna.knutsson@protonmail.com>.
