QT_TRANSLATE_NOOP("currencies.xml", "U.S. Dollar")
QT_TRANSLATE_NOOP("currencies.xml", "Japansese Yen")
QT_TRANSLATE_NOOP("currencies.xml", "Bulgarian Lev")
QT_TRANSLATE_NOOP("currencies.xml", "Czech Koruna")
QT_TRANSLATE_NOOP("currencies.xml", "Danish Krone")
QT_TRANSLATE_NOOP("currencies.xml", "British Pound")
QT_TRANSLATE_NOOP("currencies.xml", "Hungarian Forint")
QT_TRANSLATE_NOOP("currencies.xml", "Polish Zloty")
QT_TRANSLATE_NOOP("currencies.xml", "Romanian New Leu")
QT_TRANSLATE_NOOP("currencies.xml", "Swedish Krona")
QT_TRANSLATE_NOOP("currencies.xml", "Swiss Franc")
QT_TRANSLATE_NOOP("currencies.xml", "Norwegian Krone")
QT_TRANSLATE_NOOP("currencies.xml", "Croatian Kuna")
QT_TRANSLATE_NOOP("currencies.xml", "Russian Ruble")
QT_TRANSLATE_NOOP("currencies.xml", "Turkish New Lira")
QT_TRANSLATE_NOOP("currencies.xml", "Australian Dollar")
QT_TRANSLATE_NOOP("currencies.xml", "Brazilian Real")
QT_TRANSLATE_NOOP("currencies.xml", "Canadian Dollar")
QT_TRANSLATE_NOOP("currencies.xml", "Chinese Yuan Renminbi")
QT_TRANSLATE_NOOP("currencies.xml", "Hong Kong Dollar")
QT_TRANSLATE_NOOP("currencies.xml", "Indonesian Rupiah")
QT_TRANSLATE_NOOP("currencies.xml", "Israeli New Sheqel")
QT_TRANSLATE_NOOP("currencies.xml", "Indian Rupee")
QT_TRANSLATE_NOOP("currencies.xml", "South Korean Won")
QT_TRANSLATE_NOOP("currencies.xml", "Mexican Peso")
QT_TRANSLATE_NOOP("currencies.xml", "Malaysian Ringgit")
QT_TRANSLATE_NOOP("currencies.xml", "New Zeeland Dollar")
QT_TRANSLATE_NOOP("currencies.xml", "Philippine Peso")
QT_TRANSLATE_NOOP("currencies.xml", "Singapore Dollar")
QT_TRANSLATE_NOOP("currencies.xml", "Thai Baht")
QT_TRANSLATE_NOOP("currencies.xml", "South African Rand")
