name: eqonomize-hk
title: Eqonomize!
version: '1.5.9'
license: GPL-2.0+
summary: Efficient and easy accounting for small households 
description: |
  Eqonomize! is a cross-platform personal accounting software, with 
  focus on efficiency and ease of use for small households.
  Eqonomize! provides a complete solution, with bookkeeping by double
  entry and support for scheduled recurring transactions, security
  investments, and budgeting. It gives a clear overview of past and
  present transactions, and development of incomes and expenses, with
  descriptive tables and charts, as well as an approximation of future
  account values.

grade: stable
confinement: strict
base: core18

apps:
  eqonomize-hk:
    command: bin/desktop-launch eqonomize
    plugs: [x11, desktop, desktop-legacy, wayland, unity7, gsettings, home, network, cups-control, removable-media]

parts:
  eqonomize:
    source: https://github.com/Eqonomize/eqonomize/releases/download/v1.5.9/eqonomize-1.5.9.tar.gz
    source-type: tar
    source-checksum: sha512/2b2fac86af8f8e73606a4c3f6b7ae420366997ba150f529ffe2dfafa5b77b55e3a928c6b84e2644cb52bce0cbc4facae51e2120ce73ef188d284f22abd7150f1
    plugin: qmake
    qt-version: qt5
    after: [desktop-qt5]
    options:
      - PREFIX=/usr
      - COMPILE_RESOURCES="yes"

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-tag: v20180201
    source-depth: 1
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - libqt5charts5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - libqt5printsupport5
      - libqt5charts5
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - qtwayland5
      - qt5-gtk-platformtheme
      - qt5-style-plugins
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
    override-build: |
      snapcraftctl build
      sed -i '/export QT_QPA_PLATFORMTHEME=appmenu-qt5/d' $SNAPCRAFT_PART_INSTALL/bin/desktop-launch
