name: eqonomize-hk
title: Eqonomize!
version: '1.5.12'
license: GPL-2.0+
summary: Efficient and easy accounting for small households 
description: |
  Eqonomize! is a cross-platform personal accounting software, with 
  focus on efficiency and ease of use for small households.
  Eqonomize! provides a complete solution, with bookkeeping by double
  entry and support for scheduled recurring transactions, security
  investments, and budgeting. It gives a clear overview of past and
  present transactions, and development of incomes and expenses, with
  descriptive tables and charts, as well as an approximation of future
  account values.

grade: stable
confinement: strict
base: core24
compression: lzo

platforms:
  amd64:
  arm64:

apps:
  eqonomize-hk:
    extensions:
      - kde-neon-6
    command: usr/bin/eqonomize
    plugs: [home, network, cups, removable-media]

parts:
  eqonomize:
    source: https://github.com/Eqonomize/eqonomize/releases/download/v1.5.12/eqonomize-1.5.12.tar.gz
    source-type: tar
    source-checksum: sha512/3d250244eae7068ac61d56168230f9acee1777a6bac36f3a73e58c7833ee1a05c415069ae85079ac1d88661d8d171a7962b3a992ffb036a6842c3550f06ece66
    plugin: qmake
    qmake-parameters:
      - COMPILE_RESOURCES="yes"
      - INSTALL_THEME_ICONS="no"
      - PREFIX=/usr
    build-environment:
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:/snap/kf6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kf6-core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/pkgconfig:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
      - PATH: /snap/kde-qt6-core24-sdk/current/usr/bin/qt6:$PATH
    build-snaps:
      - core24
      - kf6-core24
    after:
      - patches
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/snap/patches/snap.patch

  patches:
    source: snap/patches
    plugin: dump
    organize:
      "*": patches/
    prime:
      - -*
