name: eqonomize-hk
title: Eqonomize!
version: '1.5.11'
license: GPL-2.0+
summary: Efficient and easy accounting for small households 
description: |
  Eqonomize! is a cross-platform personal accounting software, with 
  focus on efficiency and ease of use for small households.
  Eqonomize! provides a complete solution, with bookkeeping by double
  entry and support for scheduled recurring transactions, security
  investments, and budgeting. It gives a clear overview of past and
  present transactions, and development of incomes and expenses, with
  descriptive tables and charts, as well as an approximation of future
  account values.

grade: stable
confinement: strict
base: core24
compression: lzo

apps:
  eqonomize-hk:
    extensions:
      - kde-neon-6
    command: usr/bin/eqonomize
    plugs: [home, network, cups, removable-media]

parts:
  eqonomize:
    source: https://github.com/Eqonomize/eqonomize/releases/download/v1.5.11/eqonomize-1.5.11.tar.gz
    source-type: tar
    source-checksum: sha512/b5b4a3737be2d6962d374fac596aeabd2053aed1f2f884588e54dfea4a450941d8777e423a05d7ced46e0e21dd469c1b9ca2a03dd066114fa75de78c6f53e0c8
    plugin: qmake
    qmake-parameters:
      - COMPILE_RESOURCES="yes"
      - PREFIX=/usr
    build-environment:
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/pkgconfig:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
      - PATH: /snap/kde-qt6-core24-sdk/current/usr/bin/qt6:$PATH
    build-snaps:
      - core24
      - kf6-core24